export const data = [
    {
        id: 1,
        noticeType: 'Lost',
        petName: 'Joey',
        images:['https://images.freeimages.com/images/large-previews/c1c/dog-1361477.jpg?fmt=webp&w=350'],
        petBreed: 'Mixed',
        petSpecie: 'Dog',
        petDescription: 'Large black and brown mixed breed, with a white patch on his front right paw',
        dateLost: '01/18/2023',
        chipNum: 1234,
        petNotes: 'Very friendly! Was last seen wearing a red collar.',
        contactNum: '123-456-7890',
        contactEmail: 'example@example.com',
        reward: true
     },
    {
        id: 2,
        noticeType: 'Lost',
        petName: 'Kingsley',
        images: ['https://media.istockphoto.com/id/1372376277/photo/happy-smiling-puppy-dog-expression-isolated-on-green-background.jpg?s=1024x1024&w=is&k=20&c=_55xX7WO5nCm0BEvTQP4eQSZoZuAuM9Pl_U8zKSBiHI=','https://images.saymedia-content.com/.image/c_limit%2Ccs_srgb%2Cq_auto:eco%2Cw_640/MTc0NDkxODAzMDMzMDE5NzUy/220-cute-white-dog-names-with-meanings-for-your-puppy.webp', 'https://cdn-prd.content.metamorphosis.com/wp-content/uploads/sites/2/2021/04/white-dog-names-1.jpg'],
        petBreed: 'White Lab',
        petSpecie: 'Dog',
        petDescription: 'Medium size (40lb) white lab with tufty ears and a pink belly',
        dateLost: '09/06/2023',
        chipNum: 1235,
        petNotes: 'Tends to be anxious so approach slowly please!',
        contactNum: `123-456-7890`,
        contactEmail: 'example@example.com',
        reward: true
    },
    {
        id: 3,
        noticeType: 'Lost',
        petName: 'Skimbleshanks',
        images:['https://images.pexels.com/photos/1170986/pexels-photo-1170986.jpeg?auto=compress&cs=tinysrgb&w=800'],
        petBreed: 'Tabby',
        petSpecie: 'Cat',
        petDescription: 'Large red and white tabby cat with white paws and green eyes',
        dateLost: '09/08/2023',
        chipNum: 1236,
        petNotes: 'Wearing a green collar. Likes to climb trees so please look in your yards',
        contactNum: `123-456-7890`,
        contactEmail: 'example@example.com',
        reward: false    
    },
    {
        id: 4,
        noticeType: 'Found',
        petName: 'Arlo',
        images:['https://images.freeimages.com/images/large-previews/c1c/dog-1361477.jpg?fmt=webp&w=350'],
        petBreed: 'Hound',
        petSpecie: 'Dog',
        petDescription: 'Medium-sized coon-hound looking guy',
        dateLost: '01/18/2023',
        chipNum: 1237,
        petNotes: 'Really friendly, found near the supermarket',
        contactNum: '123-456-7890',
        contactEmail: 'example@example.com',
        reward: false
     }
]